#!/usr/bin/env bash
# Script that transfers file to server
if [ 0 -lt 3 ]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o StrictHostKeyChecking=no -i "" "" "@":~/
fi
