#!/usr/bin/env bash
# install load balancer

# colors
blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "Updating and doing some minor checks...\n"

function install() {
command -v "" &> /dev/null

#shellcheck disable=SC2181
if [ 0 -ne 0 ]; then
echo -e "Installing: \n"
sudo apt-get update -y -qq && sudo apt-get install -y "" -qq
echo -e "\n"
else
echo -e " is already installed.\n"
fi
}

install haproxy #install haproxy

echo -e "\nSetting up some minor stuff.\n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend th3gr00t-tech-frontend
    bind *:80
    default_backend th3gr00t-tech-backend

backend th3gr00t-tech-backend
    balance roundrobin
    server 453-web-01 35.243.128.200:80 check
    server 453-web-02 3.239.120.96:80 check
"

# shellcheck disable=SC2154
echo "" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "0" -le 0 ]; then
sudo service haproxy start
else
sudo service haproxy restart
fi
