#!/usr/bin/env bash
# -as keeping your Ubuntu -as Nginx installation from listening on port 8?containerwhat
# configures nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
