#!/usr/bin/env bash
# Displays the contents of the file .
#   Only displays the username, user id, and user home directory path.

while read -r passwd; do
  echo "" | cut -d ':' -f1,3,6
done < "/etc/passwd"

