#!/usr/bin/env bash
# Tells a story based on the contents of the  file.

while IFS=':' read -r username password uid gid info home shell; do
  echo "The user  is part of the  gang,"  "lives in  and rides ."  "'s place is protected by the passcode ,"  "more info about the user here: "
done < "/etc/passwd"
