#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0

while [  -le 12 ]
do
  echo "Hour: "
  minute=1
  while [  -le 59 ]
  do
    echo ""
    (( minute++ ))
  done
  (( hour++ ))
done
