#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

list=-
0-RSA_public_key.pub
1-for_best_school
2-while_best_school
3-until_best_school
4-if_9_say_hi
5-4_bad_luck_8_is_your_chance
6-superstitious_numbers
7-clock
a
for i in ; do
  echo "" | cut -d '-' -f2
done
